#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<sys/socket.h>
#include <arpa/inet.h>
#include <strings.h>
#include <string.h>
#include <unistd.h>
#include<netinet/in.h>
#include<gmp.h>
int main(int argc, char** argv)
{
	int alice, bob;

	alice = socket(AF_INET, SOCK_STREAM, 0);

	struct sockaddr_in server_alice;
	server_alice.sin_family = AF_INET;
	server_alice.sin_port = htons(atoi(argv[2]));
	server_alice.sin_addr.s_addr = inet_addr(argv[1]);
	bzero(&server_alice.sin_zero, 8);

	FILE *received_x = fopen("received_x", "w"); //file to write randomly generated x_0, x_1 received from Alice


	if(connect(alice, (struct sockaddr*)&server_alice, sizeof(struct sockaddr_in)) == -1){
		perror("Connection could not be established!");
		exit(0);
	}
	else
	{
		printf("Connection established!\n");
	}

	FILE *bob_c = fopen("bob_c.txt", "r"); //file to read c generated by Bob
	FILE *randomx = fopen("randomx.txt", "w"); //to store x_0 and x_1
	FILE *enc_messages = fopen("enc_messages", "w");

	char *x_0 = (char*) malloc(500*sizeof(char));
	char *x_1 = (char*) malloc(500*sizeof(char));
	char *md_0 = (char*) malloc(500*sizeof(char));
	char *md_1 = (char*) malloc(500*sizeof(char));
	char *c = (char*) malloc(500*sizeof(char));
	fgets(c, 500, bob_c);

	//Receive x_0 and x_1
	recv(alice, x_0, 500, 0);
	recv(alice, x_1, 500, 0);
	fprintf(randomx, "%s\n", x_0);
	fprintf(randomx, "%s\n", x_1);

	/***********************************************
	//Execute bob_ot1.c here.
	************************************************/

	//Sending c
	printf("Sending c...\n");
	send(alice, c, 500, 0);

	//Receive m'_0 and m'_1
	recv(alice, md_0, 500, 0);
	recv(alice, md_1, 500, 0);
	fprintf(enc_messages, "%s\n", md_0);
	fprintf(enc_messages, "%s\n", md_1);
	/***********************************************
	//Execute bob_ot2.c here.
	************************************************/
	
	close(alice);
}