#include<stdio.h>
#include<stdlib.h>

#include<sys/types.h>
#include<sys/socket.h>
#include <arpa/inet.h>
#include <strings.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h> /* for pid_t */
#include <sys/wait.h> /* for wait */

#include<netinet/in.h>

int main(int argc, char** argv)
{
	int alice,bob;

	FILE *c_out, *enc_messages, *random;

	alice = socket(AF_INET, SOCK_STREAM, 0);

	struct sockaddr_in server_alice;
	server_alice.sin_family=AF_INET;
	server_alice.sin_port=htons(atoi(argv[2]));
	server_alice.sin_addr.s_addr=inet_addr(argv[1]);
	bzero(&server_alice.sin_zero, 8);

	if(connect(alice, (struct sockaddr*)&server_alice, sizeof(struct sockaddr_in)) == -1){
		printf("Connection could not be established!");
		exit(-1);
	}

	char *buffer;
	buffer=(char*)malloc(350*sizeof(char));

	//Recieves random strings from alice and writes to randomx.txt
	random = fopen("randomx.txt", "w");

	recv(alice, buffer, 350, 0);
	fprintf(random,"%s\n",buffer);
	bzero(buffer, strlen(buffer));

	recv(alice, buffer, 350, 0);
	fprintf(random,"%s",buffer);
	bzero(buffer, strlen(buffer));

	//Fork to execute bob1
	pid_t pid=fork();

	//child process
	if(pid==0)
	{
		//Execute bob1
		static char *argv[]={"bob1",NULL};
		execv("bob1", argv);
		exit(-1);
	}

	//Waits for child process to finish
	waitpid(pid,0,0);

	//Sends the c generated by bob1 to alice
	c_out = fopen("bob_c.txt", "r");

	fscanf(c_out, "%s", buffer);
	send(alice, buffer, strlen(buffer), 0);
	bzero(buffer, strlen(buffer));

	

	enc_messages = fopen("enc_messages.txt", "w");

	recv(alice, buffer, 350, 0);
	fprintf(enc_messages,"%s\n",buffer);
	bzero(buffer, strlen(buffer));

	recv(alice, buffer, 350, 0);
	fprintf(enc_messages,"%s",buffer);
	bzero(buffer, strlen(buffer));

	//Fork to execute bob2
	pid=fork();

	//child process
	if(pid==0)
	{
		//child process bob2
		static char *argv[]={"bob2",NULL};
		execv("bob2", argv);
		exit(-1);
	}

	//Waits for child process to finish
	waitpid(pid,0,0);


	close(alice);
}