#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<sys/socket.h>
#include <arpa/inet.h>
#include <strings.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h> /* for pid_t */
#include <sys/wait.h> /* for wait */
#include<netinet/in.h>
#define BUFFER_SIZE 350

int main(int argc, char** argv)
{
	int alice,bob;
	FILE *c_out, *enc_messages, *random, *message;

	//Creating socket Alice
	alice = socket(AF_INET, SOCK_STREAM, 0);

	//Setting necessary values for the server (ip address and port no. are received as command line arguments)
	struct sockaddr_in server_alice;
	server_alice.sin_family=AF_INET;
	server_alice.sin_port=htons(atoi(argv[2]));
	server_alice.sin_addr.s_addr=inet_addr(argv[1]);
	bzero(&server_alice.sin_zero, 8);

	//Connecting to Alice
	if(connect(alice, (struct sockaddr*)&server_alice, sizeof(struct sockaddr_in)) == -1){
		printf("Connection could not be established!");
		exit(-1);
	}

	printf("Connection to Alice successful\n");

	
	//Buffer of length BUFFER_SIZE is used to send and recieve messages
	char *buffer;
	buffer=(char*)malloc(BUFFER_SIZE*sizeof(char));

	
	//text file that stores the random numbers generatd by alice
	random = fopen("randomx.txt", "w");

	//Recieves the random strings from alice and writes to text file
	recv(alice, buffer, BUFFER_SIZE, 0);
	fprintf(random,"%s\n",buffer);
	bzero(buffer, strlen(buffer));
	recv(alice, buffer, BUFFER_SIZE, 0);
	fprintf(random,"%s",buffer);
	bzero(buffer, strlen(buffer));

	fclose(random);
	printf("Randomly generated strings recieved from ALice\n");

	
	//Fork to execute bob1
	pid_t pid=fork();

	//child process
	if(pid==0)
	{
		//Execute bob1
		static char *argv[]={"bob1",NULL};
		execv("bob1", argv);
		exit(-1);
	}

	//Waits for child process to finish
	wait(NULL);

	//text file that contains the c generated by bob
	c_out = fopen("bob_c.txt", "r");

	//Sends the c generated by bob1 to alice
	fscanf(c_out, "%s", buffer);
	send(alice, buffer, BUFFER_SIZE, 0);
	bzero(buffer, strlen(buffer));
	
	fclose(c_out);
	printf("c sent to ALice\n");

	
	//text file that stores encrypted messages
	enc_messages = fopen("enc_messages.txt", "w");

	//receives the encrypted messages generated by Alice and stores in text file
	recv(alice, buffer, BUFFER_SIZE, 0);
	fprintf(enc_messages,"%s\n",buffer);
	bzero(buffer, strlen(buffer));
	recv(alice, buffer, BUFFER_SIZE, 0);
	fprintf(enc_messages,"%s",buffer);
	bzero(buffer, strlen(buffer));

	fclose(enc_messages);
	printf("Encrypted messages recieved from Alice\n");

	
	//Fork to execute bob2
	pid=fork();

	//child process
	if(pid==0)
	{
		//child process bob2
		static char *argv[]={"bob2",NULL};
		execv("bob2", argv);
		exit(-1);
	}

	//Waits for child process to finish
	wait(NULL);

	
	//close socket alice
	close(alice);
	printf("Transfer complete\n");

	
	//Display the recieved number stored in bob_message.txt
	message = fopen("bob_message.txt","r");
	fscanf(message,"%s", buffer);
	printf("Number recieved from ALice is: %s\n", buffer);
}